config/routes.rb
Rails.application.routes.draw do

  get 'cart/overview'

  get 'cart/checkout', as: 'checkout'

  get 'cart/status'

  get 'products/index'

  get 'products/create'

  get 'products/update'

  get 'static_pages/index'

  root 'static_pages#index'

  match 'auth_payment', to: 'payments#new', as: 'payment', via: [:post]

  devise_for :customers #, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

end

app/models/address.rb
class Address < ActiveRecord::Base

  belongs_to :customer
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email, :password

  after_create :create_stripe_customer

  def create_stripe_customer
    customer = Stripe::Customer.create(
      email: self.email
    )

    self.update_attribute(:stripe_customer_id, customer.id)
  end

  def add_card(card_hash)
    customer =  Stripe::Customer.retrieve( self.stripe_customer_id )
    card = customer.sources.create(
        :source => {
            :object => 'card',
            :number => card_hash[:number],
            :cvc => card_hash[:cvc],
            :exp_month => card_hash[:exp_month],
            :exp_year => card_hash[:exp_year]
        }
    )
    result = self.payment_cards.create(
      last4: card.last4,
      brand: card.brand,
      funding: card.funding,
      exp_month: card.exp_month,
      exp_year: card.exp_year,
      fingerprint: card.fingerprint,
      country: card.country
    )

  end

  def card_exists?(card_hash)
    card_token = Stripe::Token.create(
        :card => card_hash
    )
    fingerprint = card_token.card.fingerprint

    customer_card = self.payment_cards.where(fingerprint: fingerprint)

    if customer_card.length > 0
      true
    else
      false
    end
  end

  def active_order
    active = self.orders.where(state: 'in_progress').last
    active ? active : false
  end

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :payment_cards
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM

  @tax_rate = SiteSettings.tax_rate ? SiteSettings.tax_rate : ENV['DEFAULT_TAX_RATE'].to_f
  @@tax_rate = @tax_rate

  scope :open_orders, -> { where(state: :in_progress) }

  aasm  column: :state, whiny_transitions: false do

    state :in_progress, initial: true
    state :processing, before_enter: :update_total!
    state :placed
    state :shipping
    state :delivered
    state :canceled
    state :returning
    state :returned

    event :process do
      transitions from: :in_progress, to: :processing
    end

    event :place do
      transitions from: :processing, to: :placed
    end

    event :ship do
      transitions from: :placed, to: :shipping
    end

    event :shipped do
      transitions from: :shipping, to: :delivered
    end

    event :return do
      transitions from: :delivered, to: :returning
    end

    event :returned do
      transitions from: :returning, to: :returned
    end

    event :cancel do
      transitions from: :in_progress, to: :canceled
    end

  end

  def update_subtotal!
    prices = []

    products.collect do |p|
      prices << p.price unless p.on_sale && p.sale_price
      if p.on_sale && p.sale_price then prices << p.sale_price end
    end

    self.update_attribute(:subtotal, BigDecimal(prices.sum))

  end

  def update_total!
    self.update_attribute(:total, (self.subtotal + self.tax))
  end

  def update_tax!
    self.update_attribute(:tax, (self.subtotal / @@tax_rate))
  end

  def update_totals!
    self.update_subtotal!
    self.update_tax!
    self.update_total!
  end


  has_many :order_items
  has_many :products, through: :order_items
  belongs_to :customer

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  validate :product_present
  validate :order_present


  private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  belongs_to :product
  belongs_to :order
end

app/models/payment_card.rb
class PaymentCard < ActiveRecord::Base
  belongs_to :customer
end

app/models/product.rb
class Product < ActiveRecord::Base


  default_scope { where(active: true) }

  belongs_to :category
  belongs_to :order
  has_many :product_images
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  mount_uploader :url, ImageUploader

  belongs_to :product
end

app/models/site_settings.rb
class SiteSettings < RailsSettings::CachedSettings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  add_breadcrumb "home", :root_path
  add_breadcrumb "cart", :cart_overview_path

  def overview
  end

  def checkout
    @active_order = current_customer.active_order if customer_signed_in?
    current_customer.active_order.update_totals! if @active_order

    add_breadcrumb "checkout", checkout_path
  end

  def status
  end

  def add_product(id)
    current_customer.active_order.products << Product.find(id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token

  def new

    @order = current_customer.orders.where(state: :in_progress).last
    @order.update_total!

    @tax = @order.tax.to_money.format

    @total = (@order.total.to_f.round(2) * 100).to_i

    Stripe.api_key = Rails.application.secrets.stripe_secret_key

    @order.state = 'processing'

    customer =  Stripe::Customer.retrieve( current_customer.stripe_customer_id )

    card_hash = {
        :number => params[:card_number],
        :cvc => params[:card_verification],
        :exp_month => params[:exp_month],
        :exp_year => params[:exp_year]
    }

    unless current_customer.card_exists?(card_hash)
      current_customer.add_card(card_hash)
    end

    charge = Stripe::Charge.create(
        :amount => @total,
        :currency => "usd",
        :customer => current_customer.stripe_customer_id
    )

    redirect_to checkout_path
    @order.state = 'processed'

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to checkout_path

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def create
  end

  def update
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @no_breadcrumbs = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def product_images(product_id, size='medium')

    images = []

    ProductImage.where(product_id: product_id).order(:primary).each do |image|
      image_path = eval("image.url.#{size}.url")
      images << image_path
    end

    images
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cart/checkout.html.slim
.container
  .row
    .col-xs-12.col-md-4
      - flash.each do |name, msg|
        = content_tag :div, msg, class: name
      .panel.panel-default.credit-card-box
        .panel-heading.display-table
          .row.display-tr
            h3.panel-title.display-td
              | Payment Details
            .display-td
              img.img-responsive.pull-right[src="http://i76.imgup.net/accepted_c22e0.png"]
        .panel-body
          = form_tag payment_path, class: "basic-grey", id: 'payment-form' do
            - if false # Error catcher
              h1.error
                | Error occurred
            .row
              .col-xs-12
                .form-group
                  label[for="cardNumber"]
                    | CARD NUMBER
                  .input-group
                    = text_field_tag :card_number, nil, class: "form-control", 'data-stripe' => "number", placeholder: 'XXXX-XXXX-XXXX-XXXX'
                    span.input-group-addon
                      i.fa.fa-credit-card
            .row
              .col-md-12
                label[for="cardExpiry"]
                  span.hidden-xs
                    | EXPIRATION
                  span.visible-xs-inline
                    | EXP
                  |  DATE
            .row
              .col-xs-6.col-md-6
                .form-group
                  = select_tag :exp_month, options_for_select(Date::MONTHNAMES.compact.each_with_index.map { |name,i| ["#{i+1} - #{name}", i+1] }), include_blank: false, "data-stripe" => "exp-month", class: "form-control span2"
              .col-xs-6.col-md-6
                .form-group
                  = select_tag :exp_year, options_for_select((Date.today.year..(Date.today.year+10)).to_a), include_blank: false, "data-stripe" => "exp-year", class: "form-control span2"
              .col-xs-5.col-md-5.pull-left
                .form-group
                  label[for="cardCVC"]
                    | CV CODE
                  = text_field_tag :card_verification, nil, class: "form-control", "data-stripe" => "cvv", placeholder: 'CVV2'
            .row
              .col-xs-12
                button.btn.btn-success.btn-lg.btn-block[type="submit"]
                  | Pay now
            .row[style="display:none;"]
              .col-xs-12
                p.payment-errors
    - if @active_order
      |  Subotal: 
      strong
        = @active_order.subtotal.to_money.format
      br
      |  Tax: 
      strong
        = @active_order.tax.to_money.format
      br
      |  Total: 
      strong
        = @active_order.total.to_money.format
      br
= javascript_include_tag "https://js.stripe.com/v2/"

app/views/cart/overview.html.slim
h1
  | Cart#overview
p
  | Find me in app/views/cart/overview.html.erb

app/views/cart/status.html.slim
h1
  | Cart#status
p
  | Find me in app/views/cart/status.html.erb

app/views/layouts/_breadcrumb_bar.html.slim
div.breadcrumb_bar
  div.container
    div.row
      div.col-md-8
        h2
          = @page_title || 'Page title'
      div.breadcrumbs.col-md-4
        = render_breadcrumbs :separator => ' / '

app/views/layouts/_header.html.slim
section.active-search-header.hidden-sm
  a.close-btn href='#'
    i.fa.fa-close
  div.container
    div.col-md-9.search-words
      | I'm looking for (a) <span class='search-item' data-search-item='item'>Shirt</span> in size
        <span class='search-item' data-search-item='size'>Medium</span> that costs between
          $<span class='search-item' data-search-item='price_low'>0</span> and
            $<span class='search-item' data-search-item='price_high'>100</span>.
              The brand I want is <span class='search-item' data-search-item='brand'>J-Crew</span>.
    div.col-md-2.col-md-offset-1
      form.active-search-form
        input.search-terms type='hidden' name='q'
        inoput.btn.btn-block.btn-lg.btn-outline  type='button' Find my stuff
.peek-container
  .peek-arrow.hidden-sm.hidden-xs
    | &nbsp;



header.main-header
  div.container-fluid
    section.row.top-row
      div.container
        div.col-md-4
          nav.std-menu.pull-left
            ul.menu
              li.welcome
                | Welcome
              li.active-search-link.second-item
                a href='#'
                  | Active Search <i class='fa fa-search-plus'></i>
        div.col-md-4.logo-center
          a.logo-link href='/'
            = image_tag 'logo.png', class: 'header-logo img-responsive'
        div.col-md-4
          nav.std-menu.pull-right
            ul.menu
              li.dropdown.languages
                a.dropdown-toggle href='#' data-toggle='dropdown'
                  | USD <i class='fa fa-chevron-down'></i>
                ul.dropdown-menu
                  li
                    a href='#' EUR
                  li
                    a href='#' MXN
                  li
                    a href='#' BRL
              - if customer_signed_in?
                li.second-item
                  = link_to 'Log out', destroy_customer_session_path, method: :delete
                li.third-item
                  a href='#' My Account
              - else
                li.second-item
                  = link_to 'Login', new_customer_session_path
  div.container-fluid
    section.row.nav-row
      div.container
        div.col-md-9
          nav#main-navigation.mega-menu.clearfix
            ul
              li.home.top-level
                = link_to 'Home', root_path
              li.top-level
                a href='#' Blog
              li.dropdown.top-level
                a.dropdown-toggle data-toggle='dropdown' role='button' href='#' Men
                ul.dropdown-menu
                  li
                    a href='#' Item 1
                  li
                    a href='#' Item 2
                  li
                    a href='#' Item 3
                  li
                    a href='#' Item 4
              li.top-level
                a href='#' Women
              li.top-level
                a href='#' Children
        div.col-md-3
          div.customer-actions
            nav.std-menu
              ul.menu
                li.menu-search.dropdown
                  a.dropdown-toggle href='#' data-toggle='dropdown' <i class='fa fa-search'></i>
                  div.dropdown-menu
                    div.dropdown-search
                      form.search-form.form-inline action='/' method='POST'
                        div.input-group
                          input.form-control type='text' placeholder='Search...'
                          div.input-group-btn
                            button.btn.btn-primary type='submit'
                              i.fa.fa-search

                li.customer-cart.dropdown
                  a.dropdown-toggle href='#' data-toggle='dropdown' <i class='fa fa-shopping-cart'></i> $128.87
                  div.dropdown-menu
                    div.dropdown-cart
                      div.items-in-cart
                        | You have <span class='item-count'>2</span> items in your cart
                      div.cart-items
                        article.item
                          div.image-container
                            img.item-image src='http://placehold.it/50x50'
                          div.content-container
                            span.item-name Sample item 1
                            span.price $32.95
                          div.close-btn
                            button.btn.btn-danger.btn-sm <i class='fa fa-trash'></i>
                        article.item
                          div.image-container
                            img.item-image src='http://placehold.it/50x50'
                          div.content-container
                            span.item-name Sample item 2
                            span.price $29.95
                          div.close-btn
                            button.btn.btn-danger.btn-sm <i class='fa fa-trash'></i>
                      div.cart-links
                        a.view-cart href='#' View Cart
                        a.checkout href='#' Checkout


                li.customer-wishlist
                  a href='#'
                    i.fa.fa-star

app/views/layouts/application.html.slim
/ Inspired by http://neighborhood.swiftideas.com/
doctype html
html
  head
    title
      | Fashion
    = stylesheet_link_tag    'application', media: 'all'
    meta[name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1"]
    = csrf_meta_tags
  body

    = render 'layouts/header'
    = render 'layouts/breadcrumb_bar' unless @no_breadcrumbs
    = yield

    = javascript_include_tag 'application'

app/views/products/create.html.slim
h1
  | Products#create
p
  | Find me in app/views/products/create.html.erb

app/views/products/index.html.slim
h1
  | Products#index
p
  | Find me in app/views/products/index.html.erb

app/views/products/update.html.slim
h1
  | Products#update
p
  | Find me in app/views/products/update.html.erb

app/views/static_pages/index.html.slim
div.homepage-slider

div.container
  div.row
    div.col-md-6.start-shopping
      section.content-box
        header.content-box__header
          h2 Start shopping
        div.content-box__content
          | Conclusion is not closest in hell, the pit, or wonderland, but everywhere.
            Not inward places or wonderland, gain the totality.
    div.col-md-6.start-selling
      section.content-box
        header.content-box__header
          h2 Start selling
        div.content-box__content
          | Conclusion is not closest in hell, the pit, or wonderland, but everywhere.
                Not inward places or wonderland, gain the totality.